// Code generated by protoc-gen-go. DO NOT EDIT.
// source: options.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NumericalUnits int32

const (
	// Should error if UNKNOWN
	NumericalUnits_UNKNOWN NumericalUnits = 0
	// Number has no units (e.g. ID).
	NumericalUnits_NO_UNITS NumericalUnits = 1
	// ====== DISTANCE METRICS =======
	// Meters
	// Display name: "m"
	NumericalUnits_M NumericalUnits = 2
	// Meters / second
	// Display name: "m/s"
	NumericalUnits_MPS NumericalUnits = 3
	// Meters / second ^ 2
	// Display name: "m/s^2"
	NumericalUnits_MPS2 NumericalUnits = 4
	// Meters / second ^ 3
	// Display name: "m/s^3"
	NumericalUnits_MPS3 NumericalUnits = 14
	// Millimeters
	// Display name: "mm"
	NumericalUnits_MM NumericalUnits = 15
	// Micrometers
	// Display name: "µm"
	NumericalUnits_UM NumericalUnits = 16
	// ==== TIME METRICS ======
	// Seconds
	// Dislay name: "s"
	NumericalUnits_S NumericalUnits = 5
	// === ANGLE METRICS ===
	// Radians
	// Display name: "rad"
	NumericalUnits_RAD NumericalUnits = 6
	// Radians / second
	// Display name: "rad/s"
	NumericalUnits_RADPS NumericalUnits = 10
	// Radians / second ^ 2
	// Display name: "rad/s^2"
	NumericalUnits_RADPS2 NumericalUnits = 11
	// Radians / second ^ 3
	// Display name: "rad/s^3"
	NumericalUnits_RADPS3 NumericalUnits = 12
	// Degrees
	// Display name: "deg"
	NumericalUnits_DEG NumericalUnits = 22
	// == MASS METRICS =========
	// Grams
	// Display name: "g"
	NumericalUnits_G NumericalUnits = 7
	// Kilograms
	// Display name: "kg"
	NumericalUnits_KG NumericalUnits = 8
	// === FREQUENCY METRICS ===
	// Hertz (1 / seconds)
	// Display name: "Hz"
	NumericalUnits_HERTZ NumericalUnits = 9
	// ==== SIZE METRICS =====
	// Pixels
	// Display name: "px"
	NumericalUnits_PIXELS NumericalUnits = 17
	// ==== POWER METRICS =====
	// Decibel Milliwatts
	// Display name: "dBm"
	NumericalUnits_DBM NumericalUnits = 18
	// Decibels / Meter ^ 2
	// Display name: "dBsm"
	NumericalUnits_DBSM NumericalUnits = 19
	// Decibel Watts
	// Display name: "dBW"
	NumericalUnits_DBW NumericalUnits = 20
	// Decibels
	// Display name: "dB"
	NumericalUnits_DB NumericalUnits = 21
	// ==== INERTIA METRICS ====
	// Kilogram * Meter ^ 2
	// Display name: "kg*m^2"
	NumericalUnits_KGM2 NumericalUnits = 23
	// ==== FORCE METRICS =====
	// Newtons / Meter
	// Display name: "N/m"
	NumericalUnits_NPM NumericalUnits = 24
	// Newton Seconds / Meter
	// Display name: "N*s/m"
	NumericalUnits_NSPM NumericalUnits = 25
	// Newtons
	// Display name: "N"
	NumericalUnits_N NumericalUnits = 26
	// Newton Meters
	// Display name: "Nm"
	NumericalUnits_NM NumericalUnits = 27
	// Newtons Meters / Second
	// Display name: "Nm/s"
	NumericalUnits_NMPS NumericalUnits = 28
)

var NumericalUnits_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "NO_UNITS",
	2:  "M",
	3:  "MPS",
	4:  "MPS2",
	14: "MPS3",
	15: "MM",
	16: "UM",
	5:  "S",
	6:  "RAD",
	10: "RADPS",
	11: "RADPS2",
	12: "RADPS3",
	22: "DEG",
	7:  "G",
	8:  "KG",
	9:  "HERTZ",
	17: "PIXELS",
	18: "DBM",
	19: "DBSM",
	20: "DBW",
	21: "DB",
	23: "KGM2",
	24: "NPM",
	25: "NSPM",
	26: "N",
	27: "NM",
	28: "NMPS",
}

var NumericalUnits_value = map[string]int32{
	"UNKNOWN":  0,
	"NO_UNITS": 1,
	"M":        2,
	"MPS":      3,
	"MPS2":     4,
	"MPS3":     14,
	"MM":       15,
	"UM":       16,
	"S":        5,
	"RAD":      6,
	"RADPS":    10,
	"RADPS2":   11,
	"RADPS3":   12,
	"DEG":      22,
	"G":        7,
	"KG":       8,
	"HERTZ":    9,
	"PIXELS":   17,
	"DBM":      18,
	"DBSM":     19,
	"DBW":      20,
	"DB":       21,
	"KGM2":     23,
	"NPM":      24,
	"NSPM":     25,
	"N":        26,
	"NM":       27,
	"NMPS":     28,
}

func (x NumericalUnits) String() string {
	return proto.EnumName(NumericalUnits_name, int32(x))
}

func (NumericalUnits) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{0}
}

// Custom FieldOptions
type FieldOptions struct {
	// Fields tagged with this will be omitted from generated schemas
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Fields tagged with this will be marked as "required" in generated schemas
	Required bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// Fields tagged with this will constrain strings using the "minLength" keyword in generated schemas
	MinLength int32 `protobuf:"varint,3,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	// Fields tagged with this will constrain strings using the "maxLength" keyword in generated schemas
	MaxLength int32 `protobuf:"varint,4,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// Fields tagged with this will constrain strings using the "pattern" keyword in generated schemas
	Pattern              string   `protobuf:"bytes,5,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{0}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *FieldOptions) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *FieldOptions) GetMinLength() int32 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *FieldOptions) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *FieldOptions) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

// Custom FileOptions
type FileOptions struct {
	// Files tagged with this will not be processed
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Override the default file extension for schemas generated from this file
	Extension            string   `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileOptions) Reset()         { *m = FileOptions{} }
func (m *FileOptions) String() string { return proto.CompactTextString(m) }
func (*FileOptions) ProtoMessage()    {}
func (*FileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{1}
}

func (m *FileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileOptions.Unmarshal(m, b)
}
func (m *FileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileOptions.Marshal(b, m, deterministic)
}
func (m *FileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileOptions.Merge(m, src)
}
func (m *FileOptions) XXX_Size() int {
	return xxx_messageInfo_FileOptions.Size(m)
}
func (m *FileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FileOptions proto.InternalMessageInfo

func (m *FileOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *FileOptions) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

// Custom MessageOptions
type MessageOptions struct {
	// Messages tagged with this will not be processed
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Messages tagged with this will have all fields marked as "required":
	AllFieldsRequired bool `protobuf:"varint,2,opt,name=all_fields_required,json=allFieldsRequired,proto3" json:"all_fields_required,omitempty"`
	// Messages tagged with this will additionally accept null values for all properties:
	AllowNullValues bool `protobuf:"varint,3,opt,name=allow_null_values,json=allowNullValues,proto3" json:"allow_null_values,omitempty"`
	// Messages tagged with this will have all fields marked as not allowing additional properties:
	DisallowAdditionalProperties bool `protobuf:"varint,4,opt,name=disallow_additional_properties,json=disallowAdditionalProperties,proto3" json:"disallow_additional_properties,omitempty"`
	// Messages tagged with this will have all nested enums encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants     bool     `protobuf:"varint,5,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageOptions) Reset()         { *m = MessageOptions{} }
func (m *MessageOptions) String() string { return proto.CompactTextString(m) }
func (*MessageOptions) ProtoMessage()    {}
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{2}
}

func (m *MessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOptions.Unmarshal(m, b)
}
func (m *MessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOptions.Marshal(b, m, deterministic)
}
func (m *MessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOptions.Merge(m, src)
}
func (m *MessageOptions) XXX_Size() int {
	return xxx_messageInfo_MessageOptions.Size(m)
}
func (m *MessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOptions proto.InternalMessageInfo

func (m *MessageOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *MessageOptions) GetAllFieldsRequired() bool {
	if m != nil {
		return m.AllFieldsRequired
	}
	return false
}

func (m *MessageOptions) GetAllowNullValues() bool {
	if m != nil {
		return m.AllowNullValues
	}
	return false
}

func (m *MessageOptions) GetDisallowAdditionalProperties() bool {
	if m != nil {
		return m.DisallowAdditionalProperties
	}
	return false
}

func (m *MessageOptions) GetEnumsAsConstants() bool {
	if m != nil {
		return m.EnumsAsConstants
	}
	return false
}

// Custom EnumOptions
type EnumOptions struct {
	// Enums tagged with this will have be encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants bool `protobuf:"varint,1,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	// Enums tagged with this will only provide string values as options (not their numerical equivalents):
	EnumsAsStringsOnly bool `protobuf:"varint,2,opt,name=enums_as_strings_only,json=enumsAsStringsOnly,proto3" json:"enums_as_strings_only,omitempty"`
	// Enums tagged with this will have enum name prefix removed from values:
	EnumsTrimPrefix bool `protobuf:"varint,3,opt,name=enums_trim_prefix,json=enumsTrimPrefix,proto3" json:"enums_trim_prefix,omitempty"`
	// Enums tagged with this will not be processed
	Ignore               bool     `protobuf:"varint,4,opt,name=ignore,proto3" json:"ignore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumOptions) Reset()         { *m = EnumOptions{} }
func (m *EnumOptions) String() string { return proto.CompactTextString(m) }
func (*EnumOptions) ProtoMessage()    {}
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{3}
}

func (m *EnumOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumOptions.Unmarshal(m, b)
}
func (m *EnumOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumOptions.Marshal(b, m, deterministic)
}
func (m *EnumOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumOptions.Merge(m, src)
}
func (m *EnumOptions) XXX_Size() int {
	return xxx_messageInfo_EnumOptions.Size(m)
}
func (m *EnumOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EnumOptions proto.InternalMessageInfo

func (m *EnumOptions) GetEnumsAsConstants() bool {
	if m != nil {
		return m.EnumsAsConstants
	}
	return false
}

func (m *EnumOptions) GetEnumsAsStringsOnly() bool {
	if m != nil {
		return m.EnumsAsStringsOnly
	}
	return false
}

func (m *EnumOptions) GetEnumsTrimPrefix() bool {
	if m != nil {
		return m.EnumsTrimPrefix
	}
	return false
}

func (m *EnumOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

var E_FieldOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         1125,
	Name:          "protoc.gen.jsonschema.field_options",
	Tag:           "bytes,1125,opt,name=field_options",
	Filename:      "options.proto",
}

var E_ManualLink = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50015,
	Name:          "protoc.gen.jsonschema.manual_link",
	Tag:           "bytes,50015,opt,name=manual_link",
	Filename:      "options.proto",
}

var E_IgnoreInAutocomplete = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50000,
	Name:          "protoc.gen.jsonschema.ignore_in_autocomplete",
	Tag:           "varint,50000,opt,name=ignore_in_autocomplete",
	Filename:      "options.proto",
}

var E_Units = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*NumericalUnits)(nil),
	Field:         50010,
	Name:          "protoc.gen.jsonschema.units",
	Tag:           "varint,50010,opt,name=units,enum=protoc.gen.jsonschema.NumericalUnits",
	Filename:      "options.proto",
}

var E_LegacyOnlyOneofName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50020,
	Name:          "protoc.gen.jsonschema.legacy_only_oneof_name",
	Tag:           "bytes,50020,opt,name=legacy_only_oneof_name",
	Filename:      "options.proto",
}

var E_FileOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*FileOptions)(nil),
	Field:         1126,
	Name:          "protoc.gen.jsonschema.file_options",
	Tag:           "bytes,1126,opt,name=file_options",
	Filename:      "options.proto",
}

var E_MessageOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageOptions)(nil),
	Field:         1127,
	Name:          "protoc.gen.jsonschema.message_options",
	Tag:           "bytes,1127,opt,name=message_options",
	Filename:      "options.proto",
}

var E_MessageManualLink = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50000,
	Name:          "protoc.gen.jsonschema.message_manual_link",
	Tag:           "bytes,50000,opt,name=message_manual_link",
	Filename:      "options.proto",
}

var E_EnumOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*EnumOptions)(nil),
	Field:         1128,
	Name:          "protoc.gen.jsonschema.enum_options",
	Tag:           "bytes,1128,opt,name=enum_options",
	Filename:      "options.proto",
}

func init() {
	proto.RegisterEnum("protoc.gen.jsonschema.NumericalUnits", NumericalUnits_name, NumericalUnits_value)
	proto.RegisterType((*FieldOptions)(nil), "protoc.gen.jsonschema.FieldOptions")
	proto.RegisterType((*FileOptions)(nil), "protoc.gen.jsonschema.FileOptions")
	proto.RegisterType((*MessageOptions)(nil), "protoc.gen.jsonschema.MessageOptions")
	proto.RegisterType((*EnumOptions)(nil), "protoc.gen.jsonschema.EnumOptions")
	proto.RegisterExtension(E_FieldOptions)
	proto.RegisterExtension(E_ManualLink)
	proto.RegisterExtension(E_IgnoreInAutocomplete)
	proto.RegisterExtension(E_Units)
	proto.RegisterExtension(E_LegacyOnlyOneofName)
	proto.RegisterExtension(E_FileOptions)
	proto.RegisterExtension(E_MessageOptions)
	proto.RegisterExtension(E_MessageManualLink)
	proto.RegisterExtension(E_EnumOptions)
}

func init() { proto.RegisterFile("options.proto", fileDescriptor_110d40819f1994f9) }

var fileDescriptor_110d40819f1994f9 = []byte{
	// 882 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0x66, 0xda, 0x26, 0x9d, 0x9c, 0x64, 0x53, 0xd7, 0xdd, 0x96, 0xa1, 0x74, 0x21, 0x0a, 0x42,
	0xaa, 0x56, 0x28, 0x2b, 0xd2, 0xbb, 0x5c, 0x91, 0x6e, 0xba, 0xa5, 0x6a, 0x67, 0x12, 0x26, 0x0d,
	0x8b, 0x56, 0x48, 0x23, 0x6f, 0xe2, 0xa4, 0x66, 0x3d, 0x76, 0x18, 0xcf, 0x40, 0xfb, 0x02, 0xfb,
	0x10, 0xf0, 0x16, 0x3c, 0xc9, 0x5e, 0x73, 0xc3, 0x0d, 0x7f, 0x8f, 0xc0, 0x25, 0xb2, 0xe7, 0xa7,
	0x09, 0xb4, 0xcd, 0xd5, 0xf8, 0x9c, 0xef, 0xfb, 0xce, 0xb1, 0x8f, 0x8f, 0xcf, 0xc0, 0x23, 0x39,
	0x8f, 0x99, 0x14, 0xaa, 0x35, 0x8f, 0x64, 0x2c, 0xf1, 0xae, 0xf9, 0x8c, 0x5b, 0x33, 0x2a, 0x5a,
	0xdf, 0x29, 0x29, 0xd4, 0xf8, 0x8a, 0x86, 0x64, 0xbf, 0x31, 0x93, 0x72, 0xc6, 0xe9, 0x33, 0x83,
	0xbe, 0x4e, 0xa6, 0xcf, 0x26, 0x54, 0x8d, 0x23, 0x36, 0x8f, 0x65, 0x94, 0x0a, 0x9b, 0x3f, 0x59,
	0x50, 0x7b, 0xc1, 0x28, 0x9f, 0xf4, 0xd3, 0x78, 0x78, 0x0f, 0xca, 0x6c, 0x26, 0x64, 0x44, 0x1d,
	0xab, 0x61, 0x1d, 0xda, 0x7e, 0x66, 0xe1, 0x7d, 0xb0, 0x23, 0xfa, 0x7d, 0xc2, 0x22, 0x3a, 0x71,
	0xd6, 0x0c, 0x52, 0xd8, 0xf8, 0x09, 0x40, 0xc8, 0x44, 0xc0, 0xa9, 0x98, 0xc5, 0x57, 0xce, 0x7a,
	0xc3, 0x3a, 0x2c, 0xf9, 0x95, 0x90, 0x89, 0x0b, 0xe3, 0x30, 0x30, 0xb9, 0xce, 0xe1, 0x8d, 0x0c,
	0x26, 0xd7, 0x19, 0xec, 0xc0, 0xe6, 0x9c, 0xc4, 0x31, 0x8d, 0x84, 0x53, 0x6a, 0x58, 0x87, 0x15,
	0x3f, 0x37, 0x9b, 0xcf, 0xa1, 0xfa, 0x82, 0x71, 0xba, 0x6a, 0x6b, 0x07, 0x50, 0xa1, 0xd7, 0x31,
	0x15, 0x8a, 0x49, 0x61, 0xf6, 0x56, 0xf1, 0x6f, 0x1d, 0xcd, 0x7f, 0x2c, 0xa8, 0xbb, 0x54, 0x29,
	0x32, 0x5b, 0x19, 0xa8, 0x05, 0x3b, 0x84, 0xf3, 0x60, 0xaa, 0xeb, 0xa1, 0x82, 0xff, 0x1c, 0x77,
	0x9b, 0x70, 0x6e, 0x2a, 0xa5, 0xfc, 0xfc, 0xdc, 0x4f, 0x41, 0x3b, 0xe5, 0x8f, 0x81, 0x48, 0x38,
	0x0f, 0x7e, 0x20, 0x3c, 0xa1, 0xca, 0x1c, 0xdf, 0xf6, 0xb7, 0x0c, 0xe0, 0x25, 0x9c, 0x7f, 0x6d,
	0xdc, 0xb8, 0x07, 0x1f, 0x4d, 0x98, 0x4a, 0xe9, 0x64, 0x32, 0x61, 0x7a, 0x27, 0x84, 0x07, 0xf3,
	0x48, 0xce, 0x69, 0x14, 0x33, 0xaa, 0x4c, 0x61, 0x6c, 0xff, 0x20, 0x67, 0x75, 0x0b, 0xd2, 0xa0,
	0xe0, 0xe0, 0xcf, 0x00, 0x53, 0x91, 0x84, 0x2a, 0x20, 0x2a, 0x18, 0x4b, 0xa1, 0x62, 0x22, 0x62,
	0x65, 0xca, 0x66, 0xfb, 0xc8, 0x20, 0x5d, 0xf5, 0x3c, 0xf7, 0x37, 0x7f, 0xb1, 0xa0, 0x7a, 0x22,
	0x92, 0x30, 0x3f, 0xf7, 0xdd, 0x6a, 0xeb, 0x6e, 0x35, 0xfe, 0x1c, 0x76, 0x0b, 0xb6, 0x8a, 0x23,
	0x26, 0x66, 0x2a, 0x90, 0x82, 0xdf, 0x64, 0xf5, 0xc0, 0x99, 0x60, 0x98, 0x42, 0x7d, 0xc1, 0x6f,
	0x74, 0x41, 0x52, 0x49, 0x1c, 0xb1, 0x30, 0x98, 0x47, 0x74, 0xca, 0xae, 0xf3, 0x82, 0x18, 0xe0,
	0x32, 0x62, 0xe1, 0xc0, 0xb8, 0x17, 0x2e, 0x61, 0x63, 0xf1, 0x12, 0x9e, 0xfe, 0xbc, 0x06, 0x75,
	0x2f, 0x09, 0x69, 0xc4, 0xc6, 0x84, 0x8f, 0x04, 0x8b, 0x15, 0xae, 0xc2, 0xe6, 0xc8, 0x3b, 0xf7,
	0xfa, 0x2f, 0x3d, 0xf4, 0x1e, 0xae, 0x81, 0xed, 0xf5, 0x83, 0x91, 0x77, 0x76, 0x39, 0x44, 0x16,
	0x2e, 0x81, 0xe5, 0xa2, 0x35, 0xbc, 0x09, 0xeb, 0xee, 0x60, 0x88, 0xd6, 0xb1, 0x0d, 0x1b, 0xee,
	0x60, 0xd8, 0x46, 0x1b, 0xd9, 0xea, 0x08, 0xd5, 0x71, 0x19, 0xd6, 0x5c, 0x17, 0x6d, 0xe9, 0xef,
	0xc8, 0x45, 0x48, 0x6b, 0x86, 0xa8, 0xa4, 0x35, 0x7e, 0xb7, 0x87, 0xca, 0xb8, 0x02, 0x25, 0xbf,
	0xdb, 0x1b, 0x0c, 0x11, 0x60, 0x80, 0xb2, 0x59, 0xb6, 0x51, 0xb5, 0x58, 0x1f, 0xa1, 0x9a, 0xe6,
	0xf6, 0x4e, 0x4e, 0xd1, 0x9e, 0xd6, 0x9e, 0xa2, 0x4d, 0x1d, 0xea, 0xfc, 0x14, 0xd9, 0x5a, 0xfa,
	0xe5, 0x89, 0x7f, 0xf9, 0x0a, 0x55, 0x34, 0x7d, 0x70, 0xf6, 0xcd, 0xc9, 0xc5, 0x10, 0x6d, 0x1b,
	0xfa, 0xb1, 0x8b, 0xb0, 0xde, 0x44, 0xef, 0x78, 0xe8, 0xa2, 0x9d, 0xd4, 0xf5, 0x12, 0x3d, 0xd6,
	0xd2, 0xde, 0x31, 0xda, 0xd5, 0xd0, 0xf9, 0xa9, 0xdb, 0x46, 0xef, 0x6b, 0xc8, 0x1b, 0xb8, 0xc8,
	0xd1, 0x2e, 0x6f, 0x38, 0x70, 0xd1, 0x07, 0x3a, 0x8d, 0x87, 0xf6, 0x35, 0xd7, 0x73, 0xd1, 0x87,
	0x06, 0xd0, 0xe7, 0x3b, 0xe8, 0x5c, 0xc1, 0x23, 0xd3, 0x9e, 0x41, 0xf6, 0xfe, 0xf1, 0x93, 0x56,
	0xfa, 0xc6, 0x5b, 0xf9, 0x1b, 0x6f, 0x2d, 0x3e, 0x67, 0xe7, 0x0f, 0xbb, 0x61, 0x1d, 0x56, 0xdb,
	0x9f, 0xb4, 0xee, 0x1c, 0x10, 0x4b, 0x5c, 0xbf, 0x36, 0x5d, 0xb0, 0x3a, 0x5f, 0x40, 0x35, 0x24,
	0x22, 0x21, 0x3c, 0xe0, 0x4c, 0xbc, 0x59, 0x95, 0xe7, 0xb7, 0xb7, 0xeb, 0xe6, 0xe1, 0x41, 0xaa,
	0xb9, 0x60, 0xe2, 0x4d, 0x67, 0x04, 0x7b, 0xe9, 0x9d, 0x06, 0x4c, 0x04, 0x24, 0x89, 0xe5, 0x58,
	0x86, 0x73, 0x4e, 0x63, 0xba, 0x2a, 0xd8, 0xbb, 0xb7, 0x69, 0xcf, 0x3c, 0x4e, 0xe5, 0x67, 0xa2,
	0xbb, 0x20, 0xee, 0x7c, 0x0b, 0xa5, 0xc4, 0xb4, 0xc5, 0x8a, 0x28, 0xbf, 0x9a, 0x28, 0xf5, 0xf6,
	0xa7, 0xf7, 0x9c, 0x7d, 0xb9, 0xc9, 0xfc, 0x34, 0x68, 0xe7, 0x12, 0xf6, 0x38, 0x9d, 0x91, 0xf1,
	0x8d, 0xe9, 0xf5, 0x40, 0x0a, 0x2a, 0xa7, 0x81, 0x20, 0xe1, 0xca, 0x4d, 0xff, 0x9e, 0x55, 0x60,
	0x27, 0x95, 0xeb, 0xf7, 0xd0, 0xd7, 0x62, 0x8f, 0x84, 0xb4, 0x33, 0x81, 0xda, 0x94, 0x71, 0x5a,
	0xdc, 0xda, 0xc1, 0x1d, 0xb1, 0x8a, 0x41, 0xe7, 0xfc, 0x99, 0x5e, 0x5a, 0xf3, 0xde, 0x4b, 0x2b,
	0xa8, 0x7e, 0x75, 0x7a, 0x6b, 0x74, 0xe6, 0xb0, 0x15, 0xa6, 0x93, 0xae, 0x48, 0xf4, 0xf1, 0xff,
	0x12, 0x2d, 0xcf, 0x42, 0xe7, 0xaf, 0x34, 0xd7, 0x7d, 0x45, 0x5a, 0x66, 0xfb, 0xf5, 0x70, 0xc9,
	0xee, 0x7c, 0x05, 0x3b, 0x79, 0xc6, 0xc5, 0x66, 0x59, 0x99, 0xf5, 0x5d, 0x56, 0xac, 0xed, 0x4c,
	0xed, 0xde, 0x76, 0xcd, 0x04, 0x6a, 0x7a, 0x54, 0x3c, 0x50, 0xaa, 0x85, 0x91, 0xe6, 0xfc, 0xfd,
	0x70, 0xa9, 0x16, 0xa8, 0x7e, 0x95, 0xde, 0x1a, 0xc7, 0xf0, 0xca, 0x6e, 0xa5, 0xbf, 0x45, 0xf5,
	0xba, 0x6c, 0xbe, 0x47, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x04, 0xfa, 0x90, 0x65, 0x54, 0x07,
	0x00, 0x00,
}
